const ADD_TODO = 'ADD_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const SET_FILTER = 'SET_FILTER';

const FILTERS = {
    ALL: 1,
    TODO: 2,
    COMPLETE: 3,
    ARCHIVE: 4
};
export { ADD_TODO, COMPLETE_TODO, DELETE_TODO, SET_FILTER, FILTERS };
